name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Use a versão do PHP que o seu projeto requer
          extensions: mbstring, intl, dom, zip

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Mestrado-Bernardo-Pedro-CDSS
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.php.exclusions=/vendor/**
            -Dsonar.sources=php
            -Dsonar.tests=tests
            -Dsonar.php.coverage.reportPaths=coverage/*.xml
